version: '2'
volumes:
   jenkinshome:
services:
   jenkinsserver:
     build: .
     restart: always
     environment:
        DOCKER_SOCKET: /var/run/docker.sock
        DOCKER_GROUP: docker
        JENKINS_USER: jenkins
        JENKINS_URL: "https://jenkins.example.com/"
        DOCKER_HOST: unix:///var/run/docker.sock
     volumes:
        - ./jenkinshome:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
#        - /usr/bin/docker:/usr/bin/docker
     cpu_quota: 50000
     mem_limit: 6G
     memswap_limit: 6G
     network_mode: "bridge"
     ports:
        - 8080:8080  
        - 50000:50000
